# Generated by Django 5.0.3 on 2024-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='users/images'),
        ),
    ]
