# Generated by Django 5.0.3 on 2024-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(null=True, upload_to='projects/images'),
        ),
    ]
