# Generated by Django 5.0.3 on 2024-03-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_donations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='donator',
            new_name='donor',
        ),
    ]
